name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: "Luca00711-patch-1"
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore flightsearcher.Wpf
    - name: Build
      run: dotnet build --no-restore flightsearcher.Wpf
    - name: setup git config
      run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "GitHub Actions Bot"
          git config user.email "luca2005.chr@gmail.com"
    - name: commit
      run: |
          # Stage the file, commit and push
          git add flightsearcher.Wpf/bin -f
          git commit -m "new build commit"
          git push -u origin "Luca00711-patch-1" -f
    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r release.zip flightsearcher.Wpf/bin/Debug/net6.0-windows/
    - name: Release
      uses: ncipollo/release-action@v1.10.0
      with:
          artifacts: "release.zip"
      
